SQL_QUERY = {
    "load_to_db": "CREATE TABLE IF NOT EXISTS user_data (id integer PRIMARY KEY, data json);",
    "get_all": "SELECT json_agg(data -> 'from_area_id') AS data,count(*),json_agg(data -> 'Car_Cancellation') AS cancel, json_agg(data -> 'mobile_site_booking') as booking from user_data GROUP BY data #>> '{from_area_id}';",
    "get_date": "select json_agg(data-> 'from_area_id') AS data,count(*),json_agg(data -> 'Car_Cancellation') AS cancel, json_agg(data -> 'mobile_site_booking') as booking from user_data where to_date(substring(data->>'booking_created' from 0 for position('/%s' in data->>'booking_created'::text)::int+5), 'MM/DD/YYYY') = to_date('%s', 'MM/DD/YYYY') GROUP BY data #>> '{from_area_id}';",
    "get_range": "select json_agg(data-> 'from_area_id') AS data,count(*),json_agg(data -> 'Car_Cancellation') AS cancel, json_agg(data -> 'mobile_site_booking') as booking from user_data where to_date(substring(data->>'booking_created' from 0 for position('/%s' in data->>'booking_created'::text)::int+5), 'MM/DD/YYYY') >= to_date('%s', 'MM/DD/YYYY') and to_date(substring(data->>'booking_created' from 0 for position('/%s' in data->>'booking_created'::text)::int+5), 'MM/DD/YYYY') <= to_date('%s', 'MM/DD/YYYY') GROUP BY data #>> '{from_area_id}';",
    "insert_data": "INSERT INTO user_data (id, data) VALUES ({0}, '{1}')",
    "user": "select json_agg(data -> 'user_id') AS user_id, count(*), json_agg(data -> 'to_area_id') from user_data where (data ->> 'from_area_id')='%s' GROUP BY data #>> '{user_id}';",
    "user_date_range": "select json_agg(data -> 'user_id') AS user_id, count(*), json_agg(data -> 'to_area_id') from user_data where (data ->> 'from_area_id')='%s' and to_date(substring(data->>'booking_created' from 0 for position('/%s' in data->>'booking_created'::text)::int+5), 'MM/DD/YYYY') >= to_date('%s', 'MM/DD/YYYY') and to_date(substring(data ->>'booking_created' from 0 for position('/%s' in data->>'booking_created'::text)::int+5), 'MM/DD/YYYY') <= to_date('%s', 'MM/DD/YYYY') GROUP BY data #>> '{user_id}';",
    "user_date": "select json_agg(data -> 'user_id') AS user_id, count(*), json_agg(data -> 'to_area_id') from user_data where (data ->> 'from_area_id')='%s' and to_date(substring(data->>'booking_created' from 0 for position('/%s' in data->>'booking_created'::text)::int+5), 'MM/DD/YYYY') = to_date('%s', 'MM/DD/YYYY') GROUP BY data #>> '{user_id}';"
}
